require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.1'

target 'ReactNativeUnsplashApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'ReactNativeUnsplashAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.

  use_flipper!({ 'Flipper' => '0.95.1', 'Flipper-Folly' => '2.6.7', 'Flipper-DoubleConversion' => '3.1.7', 'Flipper-RSocket' => '1.4.3'})
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
    end
    # flipper_post_install(installer)
    react_native_post_install(installer)
  end

  # use_flipper!({ 'Flipper-Folly' => '2.6.7', 'Flipper' => '0.95.0', 'Flipper-RSocket' => '1.4.3', 'Flipper-DoubleConversion' => '3.1.7' })
  # post_install do |installer|
  #   react_native_post_install(installer)
  # end
end